language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-21.1.1
    - android-21
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew build connectedCheck